# https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html

cluster.name: "zjusct-observability"
node.name: "elasticsearch"
network.host: elasticsearch
discovery.type: single-node

# https://discuss.elastic.co/t/disable-authentification-for-elasticsearch/304862/3
xpack.security.enabled: false
xpack.security.enrollment.enabled: false