# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
# https://github.com/prometheus/prometheus/tree/main/documentation/examples
# changed to remote write
#global:
#  scrape_interval: 15s 
#  evaluation_interval: 15s 

#scrape_configs:
#  - job_name: 'otelcol'
#    honor_labels: true # this is a gateway
#    honor_timestamps: true
#    static_configs:
#      - targets:
#          - otelcol:9090

# https://prometheus.io/docs/guides/opentelemetry/
storage:
  tsdb:
    out_of_order_time_window: 30m
#otlp:
#  promote_resource_attributes:
#    - deployment.environment
#    - service.instance.id
#    - service.name
#    - service.namespace
#    - container.name