{
 "title": "OpenTelemetry Collector Checker",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "HTTP Checker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(http_url) (httpcheck_duration_milliseconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(http_url, error_message) (httpcheck_error)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TCP Checker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  { "title": "TLS Checker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "ZJUSCT Managed",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(tlscheck_endpoint, tlscheck_x509_cn, tlscheck_x509_issuer) (tlscheck_time_left_seconds)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}