{
 "title": "OpenTelemetry NetFlow Receiver",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "grafana-clickhouse-datasource" },
   {
    "name": "cloud_region",
    "label": "Cloud Region",
    "query": "SELECT ResourceAttributes ['cloud.region'] AS cloud_region\nFROM otel_logs\nWHERE (\n    Timestamp >= $__fromTime\n    AND Timestamp <= $__toTime\n  )\n  AND (NOT empty(cloud_region))\nGROUP BY cloud_region;"
   },
   {
    "name": "flow_sampler_address",
    "label": "Flow Sampler Address",
    "query": "SELECT LogAttributes ['flow.sampler_address'] AS flow_sampler_address\nFROM otel_logs\nWHERE (\n    Timestamp >= $__fromTime\n    AND Timestamp <= $__toTime\n  )\n  AND ScopeName = 'otelcol/netflowreceiver'\n  AND (\n    '$cloud_region' = 'ALL'\n    OR ResourceAttributes ['cloud.region'] = '$cloud_region'\n  )\nGROUP BY flow_sampler_address;"
   },
   {
    "name": "flow_type",
    "label": "Flow Type",
    "query": "SELECT LogAttributes ['flow.type'] AS flow_type\nFROM otel_logs\nWHERE (\n    Timestamp >= $__fromTime\n    AND Timestamp <= $__toTime\n  )\n  AND ScopeName = 'otelcol/netflowreceiver'\n  AND (\n    '$cloud_region' = 'ALL'\n    OR ResourceAttributes ['cloud.region'] = '$cloud_region'\n  )\nGROUP BY flow_type;"
   },
   {
    "name": "transport_type",
    "label": "Transport Type",
    "query": "SELECT LogAttributes ['network.transport'] AS transport_type\nFROM otel_logs\nWHERE (\n    Timestamp >= $__fromTime\n    AND Timestamp <= $__toTime\n\n  )\n  AND ScopeName = 'otelcol/netflowreceiver'\n  AND (\n    '$cloud_region' = 'ALL'\n    OR ResourceAttributes ['cloud.region'] = '$cloud_region'\n  )\nGROUP BY transport_type;"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Flow",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT concat(\n    LogAttributes ['source.address'],\n    ':',\n    LogAttributes ['source.port'],\n    ' -> ',\n    LogAttributes ['destination.address'],\n    ':',\n    LogAttributes ['destination.port']\n  ) AS flow,\n  LogAttributes ['flow.io.bytes'] AS total_bytes,\n  LogAttributes ['flow.io.packets'] AS total_packets,\n  fromUnixTimestamp(\n    intDiv(\n      toUInt64(LogAttributes ['flow.start']),\n      1000000000\n    )\n  ) AS start_time,\n  fromUnixTimestamp(\n    intDiv(toUInt64(LogAttributes ['flow.end']), 1000000000)\n  ) AS end_time,\n  intDiv(\n    (\n      toUInt64(LogAttributes ['flow.end']) - toUInt64(LogAttributes ['flow.start'])\n    ),\n    1000000000\n  ) AS duration,\n  if(\n    duration = 0,\n    0,\n    toUInt64(LogAttributes ['flow.io.bytes']) / duration\n  ) AS average_speed\nFROM otel_logs\nWHERE (\n    Timestamp >= $__fromTime\n    AND Timestamp <= $__toTime\n  )\n  AND ScopeName = 'otelcol/netflowreceiver'\n  AND (\n    '$cloud_region' = 'ALL'\n    OR ResourceAttributes ['cloud.region'] = '$cloud_region'\n  )\n  AND (\n    '$flow_sampler_address' = 'ALL'\n    OR LogAttributes ['flow.sampler_address'] = '$flow_sampler_address'\n  )\n  AND (\n    '$flow_type' = 'ALL'\n    OR LogAttributes ['flow.type'] = '$flow_type'\n  )\n  AND (\n    '$transport_type' = 'ALL'\n    OR LogAttributes ['network.transport'] = '$transport_type'\n  )\nORDER BY average_speed DESC\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Transport Type Volume",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sumIf(\n    toUInt64(LogAttributes ['flow.io.bytes']),\n    LogAttributes ['network.transport'] = 'icmp'\n  ) AS icmp,\n  sumIf(\n    toUInt64(LogAttributes ['flow.io.bytes']),\n    LogAttributes ['network.transport'] = 'udp'\n  ) AS udp,\n  sumIf(\n    toUInt64(LogAttributes ['flow.io.bytes']),\n    LogAttributes ['network.transport'] = 'tcp'\n  ) AS tcp\nFROM otel_logs\nWHERE (\n    Timestamp >= $__fromTime\n    AND Timestamp <= $__toTime\n  )\n  AND ScopeName = 'otelcol/netflowreceiver'\n  AND (\n    '$cloud_region' = 'ALL'\n    OR ResourceAttributes ['cloud.region'] = '$cloud_region'\n  )\n  AND (\n    '$flow_sampler_address' = 'ALL'\n    OR LogAttributes ['flow.sampler_address'] = '$flow_sampler_address'\n  )\n  AND (\n    '$flow_type' = 'ALL'\n    OR LogAttributes ['flow.type'] = '$flow_type'\n  );"
    }
   ]
  },
  {
   "title": "Top Dst with Src (Avg.)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT concat(\n    LogAttributes ['source.address'],\n    ':',\n    LogAttributes ['source.port'],\n    ' -> ',\n    LogAttributes ['destination.address'],\n    ':',\n    LogAttributes ['destination.port']\n  ) AS flow,\n  sum(toUInt64(LogAttributes ['flow.io.bytes'])) AS total_bytes,\n  sum(toUInt64(LogAttributes ['flow.io.packets'])) AS total_packets,\n  sum(toUInt64(LogAttributes ['flow.io.bytes'])) / (($__toTime - $__fromTime)) AS bytes_per_second\nFROM otel_logs\nWHERE (\n    Timestamp >= $__fromTime\n    AND Timestamp <= $__toTime\n  )\n  AND ScopeName = 'otelcol/netflowreceiver'\n  AND (\n    '$cloud_region' = 'ALL'\n    OR ResourceAttributes ['cloud.region'] = '$cloud_region'\n  )\n  AND (\n    '$flow_sampler_address' = 'ALL'\n    OR LogAttributes ['flow.sampler_address'] = '$flow_sampler_address'\n  )\n  AND (\n    '$flow_type' = 'ALL'\n    OR LogAttributes ['flow.type'] = '$flow_type'\n  )\n  AND (\n    '$transport_type' = 'ALL'\n    OR LogAttributes ['network.transport'] = '$transport_type'\n  )\nGROUP BY flow\nORDER BY bytes_per_second DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Top Destination (Avg.)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT concat(\n    LogAttributes ['destination.address'],\n    ':',\n    LogAttributes ['destination.port']\n  ) AS destination,\n  sum(toUInt64(LogAttributes ['flow.io.bytes'])) AS total_bytes,\n  sum(toUInt64(LogAttributes ['flow.io.packets'])) AS total_packets,\n  sum(toUInt64(LogAttributes ['flow.io.bytes'])) / (($__toTime - $__fromTime)) AS bytes_per_second\nFROM otel_logs\nWHERE (\n    Timestamp >= $__fromTime\n    AND Timestamp <= $__toTime\n  )\n  AND ScopeName = 'otelcol/netflowreceiver'\n  AND (\n    '$cloud_region' = 'ALL'\n    OR ResourceAttributes ['cloud.region'] = '$cloud_region'\n  )\n  AND (\n    '$flow_sampler_address' = 'ALL'\n    OR LogAttributes ['flow.sampler_address'] = '$flow_sampler_address'\n  )\n  AND (\n    '$flow_type' = 'ALL'\n    OR LogAttributes ['flow.type'] = '$flow_type'\n  )\n  AND (\n    '$transport_type' = 'ALL'\n    OR LogAttributes ['network.transport'] = '$transport_type'\n  )\nGROUP BY destination\nORDER BY bytes_per_second DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Top Source (Avg.)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT concat(\n    LogAttributes ['source.address'],\n    ':',\n    LogAttributes ['source.port']\n  ) AS source,\n  sum(toUInt64(LogAttributes ['flow.io.bytes'])) AS total_bytes,\n  sum(toUInt64(LogAttributes ['flow.io.packets'])) AS total_packets,\n  sum(toUInt64(LogAttributes ['flow.io.bytes'])) / (($__toTime - $__fromTime)) AS bytes_per_second\nFROM otel_logs\nWHERE (\n    Timestamp >= $__fromTime\n    AND Timestamp <= $__toTime\n  )\n  AND ScopeName = 'otelcol/netflowreceiver'\n  AND (\n    '$cloud_region' = 'ALL'\n    OR ResourceAttributes ['cloud.region'] = '$cloud_region'\n  )\n  AND (\n    '$flow_sampler_address' = 'ALL'\n    OR LogAttributes ['flow.sampler_address'] = '$flow_sampler_address'\n  )\n  AND (\n    '$flow_type' = 'ALL'\n    OR LogAttributes ['flow.type'] = '$flow_type'\n  )\n  AND (\n    '$transport_type' = 'ALL'\n    OR LogAttributes ['network.transport'] = '$transport_type'\n  )\nGROUP BY source\nORDER BY bytes_per_second DESC\nLIMIT 5;"
    }
   ]
  }
 ]
}