{
 "title": "SNMP PDU Metrics",
 "tags": [
  "infrastructure",
  "snmp",
  "otelcol",
  "prometheus"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PDU Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pdu_power_watt{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Power",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(pdu_power_watt{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pdu_energy_kWh{pdu_port_type=\"input\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pdu_energy_kWh{pdu_port_type=\"input\"}[1d])) * 0.58",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily CO₂ Emissions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pdu_energy_kWh{pdu_port_type=\"input\"}[1d])) * 0.5422",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monthly Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pdu_energy_kWh{pdu_port_type=\"input\"}[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pdu_energy_kWh{pdu_port_type=\"input\"}[30d])) * 0.58",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monthly CO₂ Emissions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pdu_energy_kWh{pdu_port_type=\"input\"}[30d])) * 0.5422 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pdu_current_ampere{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yearly Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pdu_energy_kWh{pdu_port_type=\"input\"}[1y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yearly Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pdu_energy_kWh{pdu_port_type=\"input\"}[1y])) * 0.58",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monthly CO₂ Emissions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pdu_energy_kWh{pdu_port_type=\"input\"}[1y])) * 0.5422 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "计算说明",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "options": {
    "content": "| 项目 | 数值 | 来源 |\n| - | - | - |\n| 电费 | 0.58元/度 | 2021年发浙大发计14号文件 |\n| 平均二氧化碳排放因子 | 0.5422 kgCO₂/kWh | 国家统计局关于发布2021年电力二氧化碳排放因子的公告，取浙江省级电力指标 |\n"
   }
  },
  {
   "title": "PDU Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pdu_power_factor_ratio{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Individual", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "PDU Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_power_watt{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Power",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_power_watt{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Energy Total",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(device_id) (pdu_energy_kWh{pdu_port_type=\"input\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Current",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_current_ampere{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Energy Delta",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(device_id) (delta(pdu_energy_kWh{pdu_port_type=\"input\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Power Factor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_power_factor_ratio{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}