{
 "title": "OpenTelemetry Collector Host Metrics Receiver",
 "tags": [
  "otelcol",
  "prometheus",
  "linux"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cloud_region", "label": "Cloud Region", "query": { "query": "label_values(cloud_region)" } },
   {
    "name": "host_name",
    "label": "Host Name",
    "query": {
     "query": "label_values({cloud_region=\"$cloud_region\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime_seconds{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Physical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_physical_count{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_logical_count{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(host_name) (sum by(cpu) (rate(system_cpu_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", state!=\"idle\"}[$__rate_interval]))) / avg by(host_name) (sum by(cpu) (rate(system_cpu_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(host_cpu_model_name) (system_cpu_frequency_hertz{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (rate(system_cpu_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization per Core",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(system_cpu_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", state!=\"idle\"}[$__rate_interval])) / sum by(cpu) (rate(system_cpu_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frequency per Core",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "sum by(cpu) (system_cpu_frequency_hertz{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "I/O Time Delta",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, sum by(device) (delta(system_disk_io_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_disk_io_bytes_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"read\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "- sum by(device) (rate(system_disk_io_bytes_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"write\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_disk_operations_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"read\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "-sum by(device) (rate(system_disk_operations_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"write\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Operation Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_disk_operation_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"read\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "-sum by(device) (rate(system_disk_operation_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"write\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Load Avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (system_cpu_load_average_1m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "1m"
    },
    {
     "expr": "sum by(host_name) (system_cpu_load_average_5m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "5m"
    },
    {
     "expr": "sum by(host_name) (system_cpu_load_average_15m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (system_cpu_load_average_1m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "1m"
    },
    {
     "expr": "sum by(host_name) (system_cpu_load_average_5m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "5m"
    },
    {
     "expr": "sum by(host_name) (system_cpu_load_average_15m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "15m"
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(mountpoint) (system_filesystem_inodes_usage{cloud_region=\"$cloud_region\", host_name=\"$host_name\", state=\"used\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(mountpoint) (system_filesystem_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\", state=\"used\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(mountpoint) (system_filesystem_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\", state=\"free\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_memory_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\", state=~\"used|free|cached|inactive\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (system_memory_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (system_memory_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Connections",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(state) (system_network_connections{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_io_bytes_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "{{device}}-receive"
    },
    {
     "expr": "sum by(device) (rate(system_network_io_bytes_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"transmit\"}[$__rate_interval])) * -1",
     "legendFormat": "{{device}}-transmit"
    }
   ]
  },
  {
   "title": "I/O Bytes Total",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(device, direction) (system_network_io_bytes_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}))",
     "legendFormat": "{{device}}-{{direction}}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_errors_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_packets_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "{{device}}-receive"
    },
    {
     "expr": "sum by(device) (rate(system_network_packets_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"transmit\"}[$__rate_interval])) * -1",
     "legendFormat": "{{device}}-transmit"
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_dropped_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Paging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (system_paging_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (rate(system_paging_faults_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(direction, type) (rate(system_paging_operations_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "{{direction}}:{{type}}"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(status) (system_processes_count{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Created Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (rate(system_processes_created_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum by(process_executable_name) (process_threads{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(process_executable_name) (topk(100, rate(process_cpu_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(process_executable_name) (process_memory_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(process_executable_name) (rate(process_disk_io_bytes_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(process_executable_name) (rate(process_disk_operations_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}