{
 "title": "OpenTelemetry Collector Container Stats Receiver",
 "tags": [
  "docker",
  "podman",
  "otelcol",
  "prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cloud_region", "label": "Cloud Region", "query": { "query": "label_values(cloud_region)" } },
   {
    "name": "host_name",
    "label": "Host Name",
    "query": {
     "query": "label_values({cloud_region=\"$cloud_region\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(container_name) (container_uptime_seconds{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\"}))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(container_name) (container_uptime_seconds{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\"}))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_file_bytes{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Block I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\", operation=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}-read"
    },
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\", operation=\"write\"}[$__rate_interval])) * -1",
     "legendFormat": "{{container_name}}-write"
    }
   ]
  },
  {
   "title": "Resource Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_uptime_seconds{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (container_memory_percent_ratio{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (container_memory_file_bytes{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\", operation=\"write\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"docker\", operation=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}