{
 "title": "ZJU Mirror",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Mirror Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Most used repos",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(\n    Timestamp,\n    -- 根据 grafana 的查询时间范围调整聚合粒度\n    toIntervalMillisecond($__interval_ms * 30)\n  ) as timestamp,\n  replaceRegexpOne(\n    -- 从 URL 中提取仓库名\n    LogAttributes ['url.path'],\n    '^/([^/]+)/.*',\n    '\\\\1'\n  ) AS repo,\n  COUNT(*)\nFROM default.otel_logs\nWHERE (\n    Timestamp >= $__fromTime\n    AND Timestamp <= $__toTime\n  )\n  AND (\n    ResourceAttributes ['cloud.region'] = 'zjusct-falcon'\n  )\n  AND (ResourceAttributes ['host.name'] = 'zjumirror')\n  AND (ResourceAttributes ['service.name'] = 'nginx-access')\n  AND (LogAttributes ['log.file.name'] = 'otel.log')\n  AND (\n    match(LogAttributes ['url.path'], '^/([^/]+)/.*')\n  )\nGROUP BY ALL -- 按请求次数降序排列，然后对每个时间段取前 5 个\nORDER BY COUNT(*) DESC\nLIMIT 5 BY timestamp;\n"
    }
   ]
  },
  { "title": "Anti Scraper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "IPv4 Request Average",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "with coords as (\n        with ip as (\n                select ip,\n                        sum(request_count) as request_count\n                from zjumirror_nginx_request_ipv4\n                where (\n                                timestamp >= $__fromTime\n                                AND timestamp <= $__toTime\n                        )\n                group by ip\n        )\n        select dictGet(\n                        'ip_trie',\n                        ('latitude', 'longitude'),\n                        tuple(ip)\n                ) as coords,\n                coords.1 as latitude,\n                coords.2 as longitude,\n                geohashEncode(longitude, latitude, 4) as geohash,\n                request_count\n        from ip\n        where longitude != 0\n                and latitude != 0\n)\nselect geohash,\n        sum(request_count) / date_diff('second', $__fromTime, $__toTime) as rps\nfrom coords\ngroup by geohash;"
    }
   ]
  },
  {
   "title": "IPv4 Bandwidth Average",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "with coords as (\n        with ip as (\n                select ip,\n                        sum(request_size) as request_size\n                from zjumirror_nginx_request_ipv4\n                where (\n                                timestamp >= $__fromTime\n                                AND timestamp <= $__toTime\n                        )\n                group by ip\n        )\n        select dictGet(\n                        'ip_trie',\n                        ('latitude', 'longitude'),\n                        tuple(ip)\n                ) as coords,\n                coords.1 as latitude,\n                coords.2 as longitude,\n                geohashEncode(longitude, latitude, 4) as geohash,\n                request_size\n        from ip\n        where longitude != 0\n                and latitude != 0\n)\nselect geohash,\n        sum(request_size) / date_diff('second', $__fromTime, $__toTime) as bandwidth\nfrom coords\ngroup by geohash;"
    }
   ]
  },
  {
   "title": "IPv4 Top Requests",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select timestamp,\n        ip,\n        request_count\nfrom zjumirror_nginx_request_ipv4\nwhere timestamp >= $__fromTime\n        AND timestamp <= $__toTime\norder by request_count desc -- 按请求数降序排列，然后对每个时间段取前 10 个\nLIMIT 10 BY timestamp;"
    }
   ]
  },
  {
   "title": "IPv4 Top Bandwidth",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "select timestamp,\n        ip,\n        request_size / 60 -- 时间戳精度为分钟，Grafana 只有 byte/s 的单位\nfrom zjumirror_nginx_request_ipv4\nwhere timestamp >= $__fromTime\n        AND timestamp <= $__toTime\norder by request_size desc -- 按带宽降序排列，然后对每个时间段取前 10 个\nLIMIT 10 BY timestamp;"
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Host CPU Load",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_load_average_5m{cloud_region=\"zjusct-falcon\", host_name=\"zjumirror\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Memory Percent",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_percent_ratio{host_name=\"zjumirror\", cloud_region=\"zjusct-falcon\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(direction) (rate(system_network_io_bytes_total{host_name=\"zjumirror\", device=\"ens160\"}[$__rate_interval]))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "Dockers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "jobs-rsync I/O rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{container_hostname=\"zjumirror\", container_name=~\"job-rsync.+\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "jobs-rsync CPU %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{container_hostname=\"zjumirror\", container_name=~\"job-rsync.+\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "jobs-ftpsync I/O rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{container_hostname=\"zjumirror\", container_name=~\"job-ftpsync.+\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "jobs-ftpsync CPU %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{container_hostname=\"zjumirror\", container_name=~\"job-ftpsync.+\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "other docker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{container_hostname=\"zjumirror\", container_name!~\"job.+\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}