# https://grafana.com/grafana/plugins/grafana-clickhouse-datasource/
apiVersion: 3
prune: true

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      host: clickhouse
      port: 9000
      username: default
      logs:
        defaultDatabase: default
        defaultTable: otel_logs
        otelEnabled: true
        otelVersion: latest
      traces:
        defaultDatabase: default
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: latest
