# https://grafana.com/docs/grafana/latest/datasources/elasticsearch/
apiVersion: 1
prune: true

datasources:
  - name: ElasticSearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      timeField: '@timestamp'