# https://grafana.com/docs/grafana/latest/datasources/prometheus/
apiVersion: 2
prune: true

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
